### ISSUE TITLE
Test code interfaces?

### ISSUE THREAD

**Issue by olale** [GraphWalker/graphwalker-example#2]
Hi!

I was looking at the java-petclinic example and while I could compile and run the tests, I could not find any definitions of the  *SharedState classes in package com.company. Am I missing something?

**Comment by KristianKarl** [comment]
Are you referring to the interfaces to the models?
If so, run ```mvn graphwalker:generate-sources``` and they will be automatically generated for you. You'll find them in the folder:
~~~
target/generated-sources/graphwalker/com/company
~~~

**Comment by olale** [comment]
Yes, that was it. I am not that used to Maven so the lack of shell completion for targets, and lack of a list of targets on the new website made me wonder.

**Comment by KristianKarl** [comment]
Glad to help. Most IDEs like IntelliJ or Eclipse, can run these maven goals, without the need of a shell.

**Comment by KristianKarl** [comment]
Glad to help. Most IDEs like IntelliJ or Eclipse, can run these maven goals, without the need of a shell.
