### ISSUE TITLE
[Help] how to display the results in pretty reports.

### ISSUE THREAD

**Issue by DeChrish** [GraphWalker/graphwalker-example#20]
After the test run, how to find out the list of the test passed/ failed in a pretty report?

**Comment by nilols** [comment]
If you execute the tests with the maven plugin you should find junit reports under the `target/graphwalker-reports` folder. 

We have a forum [here](https://groups.google.com/forum/#!forum/graphwalker) where you can ask questions like this. So I'll close this issue and if you have other questions or follow up questions to this please try the forum =)
