### ISSUE TITLE
The "PetClinicSharedState.graphml " will generate path infinitely 

### ISSUE THREAD

**Issue by edwardguo0123** [GraphWalker/graphwalker-example#21]
Hi, thank you for this project.
I just met one issue that when I used command "java -jar graphwalker-cli-4.0.0-SNAPSHOT.jar offline --start-element v_HomePage --model PetClinicSharedState.graphml "random(edge_coverage(100))"
to generate test paths, there seems no ending for its generation, but all edges should have been covered. 
When I use similar command to generate cases for on model created by myself(Device.zip), seem it is also infinite. Is there any way to stop that?
![capture](https://user-images.githubusercontent.com/27480110/44068594-61da2558-9fad-11e8-9fba-1596356b3a92.JPG)
[Device.zip](https://github.com/GraphWalker/graphwalker-example/files/2285283/Device.zip)

**Comment by edwardguo0123** [comment]
I have tried to use "Guard" and "Action" to stop that, it could work, but an error is always thrown : {"currentElementName":"v_0_Device"}
{"currentElementName":"e_POST"}
{"currentElementName":"v_1_Device"}
{"currentElementName":"e_DELETE"}
{"currentElementName":"v_0_Device"}
An error occurred when running 
[DeviceWithGuardAndAction.zip](https://github.com/GraphWalker/graphwalker-example/files/2285345/DeviceWithGuardAndAction.zip)
command: offline --start-element v_0_Device --model Device.graphml random(edge_coverage(100))
null

My updated model is attached as DeviceWithGuardAndAction

**Comment by nilols** [comment]
Hi, in your Device 2.graphml, it looks like you try to assign your **put** variable inside a guard, is that intended?
![image](https://user-images.githubusercontent.com/1027531/44070808-2735b132-9f86-11e8-9e88-492dd4b1280b.png)

**Comment by edwardguo0123** [comment]
Yes, it should not have been put there. I mainly tested that the infinite loop would be stopped by someway, but doing that seems has caused an error. I found if there is one loop in the model without stop condition, seems the path generation will always continue, just as the new model attached(SingleLoop.zip). Just do not know why, is there any other way except for the "random(edge_coverage(100))" that will cover all paths and can stop? Thank you for your attention though.

I am using following command now
[SingleLoop.zip](https://github.com/GraphWalker/graphwalker-example/files/2288964/SingleLoop.zip)
:
java -jar graphwalker-cli-4.0.0-SNAPSHOT.jar offline --start-element v_0_Device --model SingleLoop.graphml "random(edge_coverage(100))"

**Comment by dorinoltean** [comment]
Run your command without a `--start element `.
`java -jar graphwalker-cli-4.0.0-SNAPSHOT.jar offline --model SingleLoop.graphml "random(edge_coverage(100))"`

**Comment by dorinoltean** [comment]
Also check http://graphwalker.github.io/amazonShoppingCart/ for example of combining Action with Guard on the same Edge `e_AddBookToCart`

**Comment by toredal** [comment]
@dorinoltean comment regarding the `--start-element` is the correct answer as to why `PetClinicSharedState.graphml` never ends. The element `e_StartBrowser` is never executed, thus 100% can never be reached.

Either loose the `--start-element` or set it to `--start-element e_StartBrowser`
