### ISSUE TITLE
Petclinic example not working with latest browser versions

### ISSUE THREAD

**Issue by karamfilovs** [GraphWalker/graphwalker-example#22]
Version of selenium dependency and bonigarcia webdriver manger should be updated for java-petclinic module.

**Comment by toredal** [comment]
@karamfilovs You can do a PR without any special privs.
I updated to [latest dependencies](https://github.com/GraphWalker/graphwalker-example/commit/cb06650014eed3e8b7107e7b78ad729c1a2aa2c9), and verified the test run under linux and windows.
Sorry for the late response. This issue fell between the cracks I'm afraid.

**Comment by karamfilovs** [comment]
@toredal  I have created a demo based on the graphwalker for one small invoicing software. You can check it out here: https://github.com/karamfilovs/devbg
It was interesting to see it working in practice. I will be glad to hear your feedback.
Lecture: https://onedrive.live.com/?authkey=%21ADIqIs8ng_pu0Wk&cid=B779033B1201E294&id=B779033B1201E294%2168246&parId=B779033B1201E294%2167869&o=OneUp
