### ISSUE TITLE
Amazon Shopping Cart - BUILD FAILURE

### ISSUE THREAD

**Issue by LucasCLeal** [GraphWalker/graphwalker-example#4]
I am trying to run the example on the GraphWalker home page following the steps listed [here](http://graphwalker.github.io/amazonShoppingCart/)

I've been trying for a week now, no luck, and i don't know what else to do.
I am running the example on a mac, with java 1.8, firefox v46 and maven 10.11.3.

this is what terminal shows: 

> 15:43:16.315 [main] DEBUG o.g.core.machine.SimpleMachine - Context: org.graphwalker.ShoppingCartTest@1ace122d
> 15:43:16.318 [main] DEBUG o.g.core.machine.ExecutionContext - Execute  num_of_books = 0.;
> 15:43:16.337 [main] DEBUG o.g.core.machine.ExecutionContext - Execute e_StartBrowser
> 15:43:16.440 [main] ERROR o.g.core.machine.ExecutionContext - The path to the driver executable must be set by the webdriver.gecko.driver system property; for more information, see https://github.com/mozilla/geckodriver. The latest version can be downloaded from https://github.com/mozilla/geckodriver/releases

I've tried downloading the webdriver.gekco.driver and set it up on the ShoppingCartTest.java, re-install everything without Homebrew (brew), checked the maven POM file, asked for different friends try the example in different machines, nothing has worked. 

I am working on my master theses and I would love to contribute with the project, but would love to request some help with the start, please.

**Comment by KristianKarl** [comment]
Hi,
Seems like your having problems with your environment. Did you had a look at this video?
https://www.youtube.com/watch?v=9IoP45r5Ap4

I don't use OSX myself, but for better help from the community, please mail the forum :-)
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/graphwalker-3

**Comment by KristianKarl** [comment]
I checked on my own linux machine, and I got the same problem. I jumped to conclusions too early. My bad.

I made a fix 593c111. Could you do a `git pull` and then `mvn clean graphwalker:test` to see if it works better now?

I verified the fix using Firefox version 48.0

**Comment by LucasCLeal** [comment]
Thanks, now it works like a breeze.
There is a minor problem with selenium and firefox right now, the firefox 48 does not support selenium (not for now), the work around is quite simple: Use an older version of Firefox (like FF45).

but again, THANKS.
