### ISSUE TITLE
Version 3.4.1 references

### ISSUE THREAD

**Issue by olale** [GraphWalker/graphwalker-example#5]
Hi Kristian,

In the modules, you still refer to version 3.4.1 of graphwalker-example. References should be updated to 3.4.2.

To fix, please apply the following patch (or manually update version numbers in the modules that still refer to 3.4.1):

[versiondiff.txt](https://github.com/GraphWalker/graphwalker-example/files/482064/versiondiff.txt)

**Comment by KristianKarl** [comment]
Hi
Thanks!! That makes totally good sense :-)
Could you do a pull request instead?
https://help.github.com/articles/about-pull-requests/

**Comment by olale** [comment]
Done.

**Comment by KristianKarl** [comment]
Big thanks!
