### ISSUE TITLE
Issues with web drivers

### ISSUE THREAD

**Issue by olale** [GraphWalker/graphwalker-example#7]
I seem to have issues with both the latest geckodriver and ChromeDriver at the moment (on OS X 10.11.6) when conducting the graphwalker tests.

Geckodriver seems to fail to detect the H2 heading (or maybe it fails on a more basic level):

`                java.lang.AssertionError: Timeout occurred while waiting for: By.tagName: h2
                	at org.junit.Assert.fail(Assert.java:88)
                	at com.company.helper.Helper.WaitForElement(Helper.java:67)
                	at com.company.modelimplementations.PetClinic.v_HomePage(PetClinic.java:49)
`

ChromeDriver does a little better, but fails to click a button:

`
  org.openqa.selenium.WebDriverException: unknown error: Element is not clickable at point (263, 528). Other element would receive the click: &lt;a class="ui-state-default" href="#"&gt;...&lt;/a&gt;
                  (Session info: chrome=53.0.2785.116)
                  (Driver info: chromedriver=2.24.417412 (ac882d3ce7c0d99292439bf3405780058fcca0a6),platform=Mac OS X 10.11.6 x86_64) (WARNING: The server did not provide any stacktrace information)
                Command duration or timeout: 32 milliseconds
                Build info: version: 'unknown', revision: 'c7b525d', time: '2016-09-01 14:57:44 -0700'
                System info: host: 'c-214-208.eduroam.liu.se', ip: '130.236.214.208', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_05'
                Driver info: org.openqa.selenium.chrome.ChromeDriver
                Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.24.417412 (ac882d3ce7c0d99292439bf3405780058fcca0a6), userDataDir=/var/folders/z0/h0wqwpqs7svd72htt7t7y2_40000gn/T/.org.chromium.Chromium.X0oeNd}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=53.0.2785.116, platform=MAC, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
                Session ID: abb130e80caa52c7cd7c7df73fbbdd25
                	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
                	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
                	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
                	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
                	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
                	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
                	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:631)
                	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:284)
                	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:84)
                	at com.company.modelimplementations.OwnerInformation.e_AddPetSuccessfully(OwnerInformation.java:81)
`

Any ideas of why?

**Comment by olale** [comment]
By.tagName does not seem to be supported in Selenium currently: https://github.com/mozilla/geckodriver/issues/230

Using By.xpath works better, but..

... the current Geckodriver gives me stale references, either by throwing exceptions or by providing me with outdated elements when navigating pages.

**Comment by olale** [comment]
Ok, ChromeDriver works, but only if click commands are changed to sendKeys(Keys.ENTER) as clickable buttons also respond to keys, luckily. GeckoDriver (latest från Github) seems to give stale references intermittently right now and seems generally unstable.

**Comment by KristianKarl** [comment]
Hi,
Try using LATEST instead for the webdriver, like:
```
<dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-java</artifactId>
    <version>LATEST</version>    <--- <version>2.53.1</version>  --->
</dependency>
```

However, as new version of Firefox are released, the webdriver might not work as expected.

**Comment by olale** [comment]
On OS X, the ChromeDriver works better, but on Linux, even the latest Chromium fails with to recognize the search field on the Veterinarians page. On OS X, Selenium LATEST + Geckodriver gives stale references to web elements (or, at least outdated references). Is there any combination of Selenium version + Web driver implementation + browser version that is currently known to work?

**Comment by olale** [comment]
By "works better", I mean that the combination OS X 10.11.6+ChromeDriver 2.24.417412+Google Chrome 53.0.2785.116 + Selenium LATEST works if I do not use By.tagName but rather By.xpath, and replace click commands with sendKeys(Keys.ENTER).

However, I'd very much like this to work in Linux Mint, but the latest Chromium and ChromeDriver do not behave the same there I'm afraid: that combination fails to recognize the search field.

**Comment by KristianKarl** [comment]
Ok, I'll try out different combinations today on my linux and windows machines

**Comment by olale** [comment]
Great, thanks!

**Comment by KristianKarl** [comment]
On Linux, I have FF 49.0 and I did not get that to work properly with any version of selenium. I get problems like connecting to an instancance, or FF not being able to connect to an URL.

On Windows using FF 47.0.1 it works nicely.

All tested using latest master

**Comment by olale** [comment]
I could connect to an instance of FF 49.0 on OS X, using the latest geckodriver from github https://github.com/mozilla/geckodriver. However, I could not make it behave sensibly with respect to resolving web elements. For instance, it could return an outdated element from an earlier DOM, and later return another value without any StaleElementException thrown.. By all means, this is not a GraphWalker bug in any way, but is there any way to use an older version of a web driver for an older version of Firefox/Chrome that is stable with some older version of Selenium, that still exists in Maven repositories? It's a little tricky when there are so many bleading-edge software components that need to cooperate :)

**Comment by KristianKarl** [comment]
I agree. For instance, running the petclinic demo, I use a 'fixed commit', or snapshot, so that we don't need to update the tests. But oc, FF, Chrome and Selenium are still moving parts....

Maybe one should a vmware or virtualbox image. Or maybe a Docker image if possible...

**Comment by olale** [comment]
Btw, did you use the most recent Geckodriver to drive Firefox 47 on Windows?

Did you have to change By.tagName or other Selenium commands?

**Comment by KristianKarl** [comment]
Could you try out https://hub.docker.com/r/graphwalker/petclinic/

I never built a docker image before, but it works on my linux box. It will run the petclinic test.

No, I get this to run reliable on Firefox 47.0.1, and selenium 2.53.1

**Comment by olale** [comment]
Your Docker image seems to work just fine. Thank you very much!

**Comment by olale** [comment]
What versions of Selenium & a web driver did you use in your image btw? We are looking at isolating the components needed and provide a custom package in our local environment.

**Comment by KristianKarl** [comment]
Selenium 2.53.1
```
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>2.53.1</version>
        </dependency>
```

**Comment by KristianKarl** [comment]
I closing this, since it's not a GraphWalker problem per se.

The new Doocker images graphwalker/petclinic and graphwalker/amazon should provide stable demo runs of the examples.

See also:
* http://graphwalker.github.io/petclinic/
* http://graphwalker.github.io/amazonShoppingCart/
